version: '3.9'
services:
  my-express-work:
    image: node:latest
    container_name: my-express-work-container
    build:
      dockerfile: Dockerfile
    ports:
    - "1111:5000"
    networks:
        - docker-workshop-network
  my-mongo-work:
    image: mongo:latest
    container_name: my-mongo-container
    ports:
      - "27019:27017"
    networks:
      - docker-workshop-network
    volumes:
      - my-mongodb-volume:/data/db

networks:
  docker-workshop-network:  
    driver: bridge

volumes:
  my-mongodb-volume:
    