name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
jobs:
  My-First-test-on-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: clone my project on Github Actions
        uses: actions/checkout@v3
