name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
jobs:
  clone-my-project-on-github-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: clone my project on Github Actions Name ^_^
              uses: actions/checkout@v3
         
  Install-dependencies:
    runs-on: ubuntu-latest
    needs: [clone-my-project-on-github-Actions]
    steps:
        - name: Install-dependencies Name ^_^
          run: npm install
  Sucess-Mession:
      runs-on: ubuntu-latest
      needs: [clone-my-project-on-github-Actions,Install-dependencies]
      steps:
          - name: Sucess Habibi Name ^_^
            run: echo Success